spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host:port/database
    username: 'your account'
    password: 'your password'
  # session 失效时间
  session:
    timeout: 86400